---

- name: Download WordPress
  get_url:
    url=https://wordpress.org/latest.tar.gz
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile:
    dest=/etc/apache2/sites-enabled/000-default.conf
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
   - restart apache

     # name: copying the database details to wordpress
  # copy:
          # src: /var/www/wordpress/wp-config.php
    # dest: /var/www/wordpress/

- name: configuring database details using template  
  template:
    src: /etc/ansible/wordpress-playbook/roles/wordpress/templates/conf.j2   
    dest: /var/www/wordpress/wp-config.php

  become: yes




